# Generated by Django 5.2 on 2025-04-24 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('professional', '0003_modelprofessional_is_active_modelspecialty_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professional.modelprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.modelpacient')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.modelspecialty')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.modelschedule')),
            ],
            options={
                'unique_together': {('schedule', 'datetime')},
            },
        ),
    ]
