# Generated by Django 5.2 on 2025-04-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patient', '0001_initial'),
        ('professional', '0003_modelprofessional_is_active_modelspecialty_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='pacient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.modelpacient'),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.modelspecialty'),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
