# Generated by Django 5.2 on 2025-05-09 02:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patient', '0002_modelpacient_plan'),
        ('professional', '0004_alter_modelprofessional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelschedule',
            name='active_days_of_week',
            field=models.CharField(default='0111110', max_length=7),
        ),
        migrations.AddField(
            model_name='modelschedule',
            name='slot_duration',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='modelschedule',
            name='time_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='modelschedule',
            name='time_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='pacient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.modelpacient'),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.modelspecialty'),
        ),
        migrations.AlterField(
            model_name='modelappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
