# Generated by Django 5.2 on 2025-05-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_modelschedule_active_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelschedule',
            name='schedule_size',
            field=models.IntegerField(default=1),
        ),
    ]
