# Generated by Django 5.2 on 2025-05-09 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_uuid_modelplan_id'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpacient',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.modelplan'),
        ),
    ]
