# Generated by Django 5.2 on 2025-05-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelplan',
            old_name='uuid',
            new_name='id',
        ),
    ]
