# Generated by Django 5.2 on 2025-04-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='ModelSpecialty',
        ),
    ]
