# Generated by Django 5.2 on 2025-04-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_rename_specialty_modelspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofessional',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelspecialty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
