# Generated by Django 5.2.4 on 2025-07-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty',
            old_name='profesionals',
            new_name='professionals',
        ),
    ]
