# Generated by Django 5.2.4 on 2025-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_rename_profesionals_specialty_professionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
